### ISSUE TITLE
typo in 3.5.1 proof of LEMMA (Uncorrelated Principal Components)

### ISSUE THREAD

**Issue by ZisenShao** [MMiDS-textbook/MMiDS-textbook.github.io#2]
![3 5 1](https://github.com/MMiDS-textbook/MMiDS-textbook.github.io/assets/128634050/ea014728-b397-4dda-b31c-e278df5ca2c1)
In the proof of LEMMA (Uncorrelated Principal Components), it says that by SVD we can get square $\sigma_1$, but in the calculate step, the square is ignored.

**Comment by sebroc** [comment]
Fixed. Thanks! -Sbt
